### PR TITLE
Updated project to allow running it with newer JVMs

### PR DESCRIPTION
**Pull request by paucls**
Updated project to target Java 8.
Updated junit.
Added mockito as dependency.

### CODE REVIEW

**Comment by xpmatteo** [comment]
Hi Paul, thanks for the PR!  An upgrade was sorely needed.

Why Mockito though?  The provided tests do not use it.

I would suggest adding also "out" to `.ignore` to avoid versioning IntelliJ output

**Comment by paucls** [comment]
Hello Matteo,
the reason for adding Mockito is to have it available for people that want to use it at some moment during the refactoring exercise. But I am more than happy to remove it from the merge request.

**Comment by paucls** [comment]
I updated the .gitignore and removed mockito.

**Comment by xpmatteo** [comment]
Thanks a million Paulo!

**Pull request merged**
